# Generated by Django 5.0.2 on 2024-02-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_code',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
